In [2]:
# How to create numpy array
import numpy as np
li= [1,2,3,4]
a= np.array(li)
# Slicing of numpy array wroks same as lists and tuple and string
a[1:3]

arr2= np.array([1,5,10])
print(arr2)

[ 1  5 10]


In [7]:
np.zeros(5)
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
arr= np.ones(10)
print(arr.dtype)

arr= np.ones(10, int)
print(arr.dtype)

float64
int32


## Multi Dimensional Array

In [18]:
arr2D= np.ones((2,2), int)
arr2D

array([[1, 1],
       [1, 1]])

In [25]:
tup= arr2D.shape
print(arr2D.shape)
type(tup)

(2, 2)


tuple

In [27]:
# Row data

a= np.array( [ [1,2,3], [4,5,6], [7,8,9], [10,11,12] ])

# complete row
print(a[0])

# complete colum

print( a[ : , 0])

[1 2 3]
[ 1  4  7 10]


In [30]:
print(a[0:2, 0])
print(a[ : , 0 : 2])

[1 4]
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]
