In [22]:
import numpy as np

a= np.array([1,2,3])
b= np.array([4,5,6])

a + 2

array([3, 4, 5])

In [5]:
print(a*2)
print(a*b)

[2 4 6]
[ 4 10 18]


In [8]:
a.mean()

2.0

In [9]:
a.sum()

6

In [7]:
a= np.array([1,2,3])
b= np.array([5,6,7])

d= ((a-b)**2).sum()
print(d)

import math as m
distance= m.sqrt(d)
print( "distance is : " , distance)

48
distance is :  6.928203230275509


In [14]:
arr= np.array([ 1, 3, 5, 6 ])

arr= arr - arr.mean()
arr= arr**2
arr= arr.sum()
print(arr)

14.75


In [21]:
arr1= np.array([ [2,2], [1,1] ])
arr2= np.array([ [1,0], [0,1] ])

arr1.dot(arr2)

array([[2, 2],
       [1, 1]])

## Matrix

In [25]:
mat= np.matrix('1,2,3; 4,5,6')
mat

matrix([[1, 2, 3],
        [4, 5, 6]])